apiVersion: v1
kind: Namespace
metadata:
  name: fargate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fargate-pods
  namespace: fargate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fargate-pods
  template:
    metadata:
      labels:
        app: fargate-pods
    spec:
      containers:
      - name: fargate-container
        image: busybox
        command: ["/bin/sh", "-c", "sleep 999999"]
        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"
          limits:
            cpu: "400m"
            memory: "256Mi"
