apiVersion: v1
kind: Namespace
metadata:
  name: scale-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress
  namespace: scale-test
spec:
  replicas: 15
  selector:
    matchLabels:
      app: cpu-stress
  template:
    metadata:
      labels:
        app: cpu-stress
    spec:
      containers:
      - name: cpu-stress
        image: busybox
        command: ["/bin/sh", "-c", "sleep 999999"]
        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"
          limits:
            cpu: "400m"
            memory: "256Mi"
