apiVersion: v1
kind: Pod
metadata:
  name: awscli
  namespace: development
spec:
  serviceAccountName: development-service-account
  containers:
  - name: awscli
    image: amazon/aws-cli:latest
    command: [ "sleep", "infinity" ]
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
  restartPolicy: Never
